# Kubernetes secrets for Claude CLI Web UI
# Note: In production, use external secret management (e.g., AWS Secrets Manager, HashiCorp Vault)

apiVersion: v1
kind: Secret
metadata:
  name: claude-cli-secrets
  namespace: claude-cli
  labels:
    app: claude-cli
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # Use: echo -n "your-secret" | base64
  
  # Application secrets
  secret-key: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u  # your-super-secret-jwt-key-change-this-in-production
  
  # Database secrets
  postgres-password: eW91ci1zZWN1cmUtcG9zdGdyZXMtcGFzc3dvcmQ=  # your-secure-postgres-password
  postgres-user: Y2xhdWRlX3VzZXI=  # claude_user
  postgres-db: Y2xhdWRlX2NsaQ==  # claude_cli
  
  # Redis secrets
  redis-password: eW91ci1zZWN1cmUtcmVkaXMtcGFzc3dvcmQ=  # your-secure-redis-password
  
  # Monitoring secrets
  grafana-admin-password: eW91ci1zZWN1cmUtZ3JhZmFuYS1wYXNzd29yZA==  # your-secure-grafana-password

---
# TLS certificate secret (if using cert-manager)
apiVersion: v1
kind: Secret
metadata:
  name: claude-cli-tls
  namespace: claude-cli
  labels:
    app: claude-cli
type: kubernetes.io/tls
data:
  # Replace with your actual certificate and key
  tls.crt: ""
  tls.key: ""